.PHONY: build run watch fmt check

build:
	cargo build -p outro_08

run:
	cargo run -p outro_08

watch:
	cargo watch -w exercises/08_futures/08_outro -x "run -p outro_08"

fmt:
	cargo fmt -p outro_08

check:
	cargo check -p outro_08
